---

- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: IPADDR
    vcenter_user: @vsphere.local
    vcenter_pass: "PWD"
    esxhost: IPADDR
    datastore: Vol_01
    vmtemplate: Windows Server 2019 Template
    name: "newvm"
    notes: Ansible Test
    dumpfacts: False
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: DC
        folder: Discovered virtual machine
        name: "{{ name }}"
        template: "{{ vmtemplate }}"
        disk:
          - size_gb: "{{ disk_size | default(250) }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
        - name: VM Network
          type: static
          ip: IPADDR
          netmask: NETMASK
          gateway: GATEWAY
          dns_servers: DNS
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: True
        state: present
      register: newvm

    - name: IP address info
      debug:
        msg: "{{ newvm.instance.ipv4 }} {{ name }}"
