---

- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: 10.20.4.56
    vcenter_user: administrator@vsphere.local
    vcenter_pass: "@peX123!"
    esxhost: 10.20.4.55
    datastore: R5_Vol_01
    vmtemplate: Windows Server 2019 Template
    name: "newvm"
    notes: Ansible Test
    dumpfacts: False
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: Apex Test
        folder: Discovered virtual machine
        name: "{{ name }}"
        template: "{{ vmtemplate }}"
        disk:
          - size_gb: "{{ disk_size | default(250) }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
        - name: VM Network
          type: static
          ip: 10.20.4.58
          netmask: 255.255.255.0
          gateway: 10.20.4.1
          dns_servers: 8.8.8.8
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: True
        state: present
      register: newvm

    - name: IP address info
      debug:
        msg: "{{ newvm.instance.ipv4 }} {{ name }}"
